ALTER TYPE TYPE_USER_STATUS RENAME TO TYPE_USER_STATUS_OLD;

CREATE TYPE TYPE_USER_STATUS AS ENUM ('PENDING',  'INCOMPLETE', 'ACTIVE', 'INACTIVE', 'ARCHIVED');

UPDATE users
SET status = 'INCOMPLETE'
WHERE status = 'INVITATION_NOT_SENT';

ALTER TABLE users
    ALTER COLUMN status TYPE TYPE_USER_STATUS USING status::text::TYPE_USER_STATUS;

DROP TYPE TYPE_USER_STATUS_OLD CASCADE;