DROP TABLE role_permission;
DROP TYPE TYPE_PERMISSION;

ALTER TYPE TYPE_ROLE RENAME TO TYPE_ROLE_OLD;

CREATE TYPE TYPE_ROLE AS ENUM ('GUEST', 'MEMBER', 'TIER_ADMIN', 'ADMIN');

ALTER TABLE user_role ALTER COLUMN role_id DROP NOT NULL;

UPDATE user_role 
SET role_id = NULL
FROM role
WHERE role.value IN ('SECURITY', 'USER_MANAGER', 'FRONT_DESK')
AND user_role.role_id = role.id;

DELETE
FROM role
WHERE value IN ('SECURITY', 'USER_MANAGER', 'FRONT_DESK');

ALTER TABLE role
    ALTER COLUMN value TYPE TYPE_ROLE USING value::text::TYPE_ROLE;

DROP TYPE TYPE_ROLE_OLD CASCADE;

INSERT INTO role VALUES (DEFAULT, 'TIER_ADMIN');

UPDATE user_role 
SET role_id = (SELECT id FROM role WHERE value = 'TIER_ADMIN')
WHERE role_id IS NULL;

ALTER TABLE user_role ALTER COLUMN role_id SET NOT NULL;